development:
  database: blog_development
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  database: blog_production
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  database: blog_test
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432
