# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce530f0d4e861aeaaff4382a29186afaaed5b6e9d8dee6584a87fb9eda3d0d5a0012cfea80b624c69c55b516c04d60bfae797160386132e64b2c881d77511d6d

test:
  secret_key_base: adc3eb830317d967ce0809651e35a6207d35c97714068a0394bf4a0527f304966d4adc76a858213547d266b02ddee8f564d3f7071fe3f45fe5e1269a673e9763

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
